// <auto-generated />
using System;
using HostelProperty.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HostelProperty.DataAccess.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250604160959_AddUser")]
    partial class AddUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HostelProperty.DataAccess.Entities.Resident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumberCourse")
                        .HasColumnType("int");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomNumber");

                    b.ToTable("Residents");
                });

            modelBuilder.Entity("HostelProperty.DataAccess.Entities.Room", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Number"));

                    b.HasKey("Number");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("HostelProperty.DataAccess.Entities.RoomSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("DateReseption")
                        .HasColumnType("date");

                    b.Property<int?>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("RoomNumber");

                    b.ToTable("RoomSubjects");
                });

            modelBuilder.Entity("HostelProperty.DataAccess.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("DateReseption")
                        .HasColumnType("date");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("HostelProperty.DataAccess.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HostelProperty.DataAccess.Entities.Resident", b =>
                {
                    b.HasOne("HostelProperty.DataAccess.Entities.Room", "Room")
                        .WithMany("Residents")
                        .HasForeignKey("RoomNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HostelProperty.DataAccess.Entities.RoomSubject", b =>
                {
                    b.HasOne("HostelProperty.DataAccess.Entities.Room", "Room")
                        .WithMany("RoomSubjects")
                        .HasForeignKey("RoomNumber");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HostelProperty.DataAccess.Entities.Subject", b =>
                {
                    b.HasOne("HostelProperty.DataAccess.Entities.Resident", "Resident")
                        .WithMany("Subjects")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("HostelProperty.DataAccess.Entities.Resident", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("HostelProperty.DataAccess.Entities.Room", b =>
                {
                    b.Navigation("Residents");

                    b.Navigation("RoomSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
